name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get git tag
      uses: little-core-labs/get-git-tag@v3.0.2
      with:
        tagRegex: "foobar-(.*)"  
        tagRegexGroup: 1 
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: arnovanliedekerke
        password: terminatort800
        logout: true
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn clean install -DskipTests
    
    - name: Build the Docker image
      run: |
        docker image build -t arnovanliedekerke/visits:$GIT_TAG_NAME .
      
    - name: Push to Docker Hub
      run: | 
        docker push arnovanliedekerke/visits:$GIT_TAG_NAME
